version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: cricket
      MYSQL_USER: user
      MYSQL_PASSWORD: user@123

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"


